### ISSUE TITLE
Using action-get-tag in workflow triggered by workflow_run

### ISSUE THREAD

**Issue by peresbruno** [dawidd6/action-get-tag#4]
Hi!

I'm trying to use this action in a workflow that is triggered via `workflow_run` as follow:

```
name: CD

on:
  workflow_run:
    workflows: ['CI']
    push:
      tags: v[1-9]+.[0-9]+.[0-9]+
    types:
      - completed

(...)

    steps:

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Use tag
        run: echo ${{steps.tag.outputs.tag}}
```

But currently, I'm getting the following error:

```
Run dawidd6/action-get-tag@v1
env:
  IMAGE_NAME: open-tuna-api
Error: Not a tag ref (refs/heads/master)
```

Why am I getting this error and how can I avoid it?

Thanks for the help!

**Comment by dawidd6** [comment]
https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_run

Judging by documentation it is not possible to filter by tags with this event.

**Comment by peresbruno** [comment]
Thanks @dawidd6 !

Do you know of any other way to achieve this goal? Maybe setting the branch name as the output of CI workflow...

**Comment by dawidd6** [comment]
I don't know all your workflows. Can't help with current knowledge.

**Comment by peresbruno** [comment]
@dawidd6 

My first workflow is triggered for new tags, as you can see:

```
name: CI

on:
  push:
    tags: v[1-9]+.[0-9]+.[0-9]+
```

The CD workflow is triggered when the previous workflow (CI) is completed.

```
name: CD

on:
  workflow_run:
    workflows: ['CI']
    push:
      tags: v[1-9]+.[0-9]+.[0-9]+
    types:
      - completed
```
